SELECT
ORDER_ID,
IFNULL(SHIPPING_SERVICE, 'Unkown') as SHIPPING_SERVICE,
IFNULL(SHIPPING_COST, '0') as SHIPPING_COST,
ADDRESS_ID,
CREATED_AT,
PROMO_ID,
ESTIMATED_DELIVERY_AT,
IFNULL(ORDER_COST,'0') AS ORDER_COST,
USER_ID,
IFNULL(ORDER_TOTAL,'0') AS ORDER_TOTAL,
DELIVERED_AT,
TRACKING_ID,
STATUS
FROM {{source("sql_server","ORDERS")}}